"""Compatibility facade for Minecraft runtime use cases."""

from app.services.log_stream_service import (
    _file_source_settings,
    crash_stop_after_grace,
    decrement_log_stream_clients,
    ensure_log_stream_fetcher_started,
    get_log_source_text,
    increment_log_stream_clients,
    is_rcon_noise_line,
    line_matches_crash_marker,
    log_source_fetcher_loop,
    log_source_settings,
    normalize_log_source,
    publish_log_stream_line,
    schedule_crash_stop_if_needed,
)
from app.services.rcon_probe_service import (
    clean_rcon_output,
    get_players_online,
    get_tick_rate,
    is_rcon_enabled,
    is_rcon_startup_ready,
    parse_players_online,
    probe_minecraft_runtime_metrics,
    probe_tick_rate,
    refresh_rcon_config,
    run_mcrcon,
)
from app.services.status_projection_service import (
    get_service_status_class,
    get_service_status_display,
)

__all__ = [
    "_file_source_settings",
    "is_rcon_noise_line",
    "normalize_log_source",
    "log_source_settings",
    "get_log_source_text",
    "publish_log_stream_line",
    "line_matches_crash_marker",
    "crash_stop_after_grace",
    "schedule_crash_stop_if_needed",
    "log_source_fetcher_loop",
    "ensure_log_stream_fetcher_started",
    "increment_log_stream_clients",
    "decrement_log_stream_clients",
    "is_rcon_startup_ready",
    "clean_rcon_output",
    "refresh_rcon_config",
    "is_rcon_enabled",
    "run_mcrcon",
    "parse_players_online",
    "probe_tick_rate",
    "probe_minecraft_runtime_metrics",
    "get_players_online",
    "get_tick_rate",
    "get_service_status_display",
    "get_service_status_class",
]
