"""Environment-backed defaults and required setup keys."""

from __future__ import annotations

from app.ports import ports

ENV_DEFAULTS = {
    "SERVICE": "minecraft",
    "DISPLAY_TZ": "Asia/Manila",
    "DOC_README_URL": "/doc/server_setup_doc.md",
    "MCWEB_REQUIRE_PASSWORD": "true",
    "MINECRAFT_ROOT_DIR": ports.service_control.default_minecraft_root(),
    "BACKUP_DIR": ports.service_control.default_backup_dir(),
    "BACKUP_INTERVAL_HOURS": "3",
    "BACKUP_WATCH_INTERVAL_ACTIVE_SECONDS": "15",
    "BACKUP_WATCH_INTERVAL_OFF_SECONDS": "45",
    "IDLE_ZERO_PLAYERS_SECONDS": "180",
    "IDLE_CHECK_INTERVAL_SECONDS": "5",
    "IDLE_CHECK_INTERVAL_ACTIVE_SECONDS": "5",
    "IDLE_CHECK_INTERVAL_OFF_SECONDS": "15",
    "CRASH_STOP_GRACE_SECONDS": "15",
    "MC_QUERY_INTERVAL_SECONDS": "3",
    "METRICS_COLLECT_INTERVAL_SECONDS": "1",
    "METRICS_COLLECT_INTERVAL_OFF_SECONDS": "5",
    "METRICS_IDLE_STORAGE_REFRESH_SECONDS": "15",
    "METRICS_STREAM_HEARTBEAT_SECONDS": "1",
    "LOG_STREAM_HEARTBEAT_SECONDS": "1",
    "LOG_STREAM_EVENT_BUFFER_SIZE": "800",
    "MINECRAFT_LOG_TEXT_LIMIT": "1000",
    "MINECRAFT_JOURNAL_TAIL_LINES": "1000",
    "MINECRAFT_LOG_VISIBLE_LINES": "500",
    "BACKUP_LOG_TEXT_LIMIT": "200",
    "MCWEB_LOG_TEXT_LIMIT": "200",
    "MCWEB_ACTION_LOG_TEXT_LIMIT": "200",
    "HOME_PAGE_ACTIVE_TTL_SECONDS": "30",
    "HOME_PAGE_HEARTBEAT_INTERVAL_MS": "10000",
    "FILE_PAGE_CACHE_REFRESH_SECONDS": "15",
    "FILE_PAGE_ACTIVE_TTL_SECONDS": "30",
    "FILE_PAGE_HEARTBEAT_INTERVAL_MS": "10000",
    "SERVICE_STATUS_CACHE_ACTIVE_SECONDS": "1",
    "SERVICE_STATUS_CACHE_OFF_SECONDS": "5",
    "SLOW_METRICS_INTERVAL_ACTIVE_SECONDS": "1",
    "SLOW_METRICS_INTERVAL_OFF_SECONDS": "15",
    "LOG_FETCHER_IDLE_SLEEP_SECONDS": "2",
    "LOG_FETCHER_IDLE_POLL_SECONDS": "15",
    "MAINTENANCE_SCOPE_BACKUP_ZIP": "true",
    "MAINTENANCE_SCOPE_STALE_WORLD_DIR": "true",
    "MAINTENANCE_SCOPE_OLD_WORLD_ZIP": "true",
    "MAINTENANCE_GUARD_NEVER_DELETE_NEWEST_N": "1",
    "MAINTENANCE_GUARD_NEVER_DELETE_LAST_BACKUP": "true",
    "MAINTENANCE_GUARD_PROTECT_ACTIVE_WORLD": "true",
}

REQUIRED_KEYS = (
    "MCWEB_SECRET_KEY",
    "MCWEB_ADMIN_PASSWORD_HASH",
    "SERVICE",
    "DISPLAY_TZ",
    "MINECRAFT_ROOT_DIR",
    "BACKUP_DIR",
)

