"""Debug server.properties key/type declarations."""

DEBUG_SERVER_PROPERTIES_KEYS = (
    "accepts-transfers",
    "allow-flight",
    "allow-nether",
    "broadcast-console-to-ops",
    "broadcast-rcon-to-ops",
    "bug-report-link",
    "difficulty",
    "enable-command-block",
    "enable-jmx-monitoring",
    "enable-query",
    "enable-rcon",
    "enable-status",
    "enforce-secure-profile",
    "enforce-whitelist",
    "entity-broadcast-range-percentage",
    "force-gamemode",
    "function-permission-level",
    "gamemode",
    "generate-structures",
    "generator-settings",
    "hardcore",
    "hide-online-players",
    "initial-disabled-packs",
    "initial-enabled-packs",
    "level-name",
    "level-seed",
    "level-type",
    "log-ips",
    "max-build-height",
    "max-chained-neighbor-updates",
    "max-players",
    "max-tick-time",
    "max-world-size",
    "motd",
    "network-compression-threshold",
    "online-mode",
    "op-permission-level",
    "pause-when-empty-seconds",
    "player-idle-timeout",
    "prevent-proxy-connections",
    "previews-chat",
    "pvp",
    "query.port",
    "rate-limit",
    "rcon.password",
    "rcon.port",
    "region-file-compression",
    "require-resource-pack",
    "resource-pack",
    "resource-pack-id",
    "resource-pack-prompt",
    "resource-pack-sha1",
    "server-ip",
    "server-port",
    "simulation-distance",
    "snooper-enabled",
    "spawn-animals",
    "spawn-monsters",
    "spawn-npcs",
    "spawn-protection",
    "sync-chunk-writes",
    "text-filtering-config",
    "text-filtering-version",
    "use-native-transport",
    "view-distance",
    "white-list",
)

DEBUG_SERVER_PROPERTIES_ENUMS = {
    "difficulty": ("peaceful", "easy", "normal", "hard"),
    "gamemode": ("survival", "creative", "adventure", "spectator"),
    "level-type": ("default", "flat", "large_biomes", "amplified", "single_biome_surface"),
    "region-file-compression": ("deflate", "lz4", "none"),
}

DEBUG_SERVER_PROPERTIES_INT_KEYS = {
    "entity-broadcast-range-percentage",
    "function-permission-level",
    "max-build-height",
    "max-chained-neighbor-updates",
    "max-players",
    "max-tick-time",
    "max-world-size",
    "network-compression-threshold",
    "op-permission-level",
    "pause-when-empty-seconds",
    "player-idle-timeout",
    "query.port",
    "rate-limit",
    "rcon.port",
    "server-port",
    "simulation-distance",
    "spawn-protection",
    "text-filtering-version",
    "view-distance",
}

DEBUG_SERVER_PROPERTIES_BOOL_KEYS = {
    "accepts-transfers",
    "allow-flight",
    "allow-nether",
    "broadcast-console-to-ops",
    "broadcast-rcon-to-ops",
    "enable-command-block",
    "enable-jmx-monitoring",
    "enable-query",
    "enable-rcon",
    "enable-status",
    "enforce-secure-profile",
    "enforce-whitelist",
    "force-gamemode",
    "generate-structures",
    "hardcore",
    "hide-online-players",
    "log-ips",
    "online-mode",
    "prevent-proxy-connections",
    "previews-chat",
    "pvp",
    "require-resource-pack",
    "snooper-enabled",
    "spawn-animals",
    "spawn-monsters",
    "spawn-npcs",
    "sync-chunk-writes",
    "use-native-transport",
    "white-list",
}
