[mypy]
python_version = 3.13
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
no_implicit_optional = True
check_untyped_defs = True
ignore_missing_imports = True

[mypy-app.ports.interfaces]
disallow_untyped_defs = True
strict = True

[mypy-app.bootstrap.config_loader]
disallow_untyped_defs = True
strict = True

[mypy-app.state.contexts]
disallow_untyped_defs = True
strict = True

[mypy-app.infrastructure.adapters]
disallow_untyped_defs = True
strict = True
