"""Application port interfaces for infrastructure dependencies."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class ServiceControlPort(Protocol):
    def default_web_port(self) -> int: ...
    def default_minecraft_root(self, *, user_name: str = "") -> str: ...
    def default_backup_dir(self, *, user_name: str = "") -> str: ...
    def resolve_backup_script_path(self, app_dir: Path | str) -> Path: ...
    def apply_process_timezone(self, tz_name: str) -> None: ...
    def is_valid_env_path(self, path_text: str) -> bool: ...
    def service_show_load_state(self, service_name: str, *, timeout: float = 5, minecraft_root: Any = None) -> Any: ...
    def service_is_active(self, service_name: str, *, timeout: float = 3, minecraft_root: Any = None) -> Any: ...
    def service_start_no_block(self, service_name: str, *, timeout: float = 12, minecraft_root: Any = None) -> Any: ...
    def service_start(self, service_name: str, *, timeout: float = 12, minecraft_root: Any = None) -> Any: ...
    def service_stop(self, service_name: str, *, timeout: float = 12, minecraft_root: Any = None) -> Any: ...
    def run_elevated(self, cmd: list[str], *, timeout: float | None = None) -> Any: ...
    def run_mcrcon(self, host: str, port: int, password: str, command: str, *, timeout: float = 4) -> Any: ...
    def is_timeout_error(self, exc: BaseException) -> bool: ...


class MetricsPort(Protocol):
    def get_cpu_usage_per_core(self) -> str: ...
    def get_ram_usage(self) -> str: ...
    def get_cpu_frequency(self) -> str: ...
    def get_storage_usage(self) -> str: ...


class LogPort(Protocol):
    def minecraft_log_stream_mode(self) -> str: ...
    def minecraft_load_recent_logs(self, service_name: str, logs_dir: Path, *, tail_lines: int = 1000, timeout: float = 4) -> str: ...
    def minecraft_startup_probe_output(self, service_name: str, logs_dir: Path, *, timeout: float = 4) -> str | None: ...
    def minecraft_follow_logs_command(self, service_name: str, logs_dir: Path) -> list[str] | None: ...
    def minecraft_open_follow_logs_process(self, service_name: str, logs_dir: Path) -> Any | None: ...
    def iter_process_lines(self, process_handle: Any) -> Any: ...
    def is_process_running(self, process_handle: Any) -> bool: ...
    def terminate_process(self, process_handle: Any) -> None: ...
    def is_timeout_error(self, exc: BaseException) -> bool: ...


class BackupPort(Protocol):
    def run_backup_script(self, script_path: Path, trigger: str, *, timeout: float = 600) -> Any: ...
    def is_timeout_error(self, exc: BaseException) -> bool: ...


class StorePort(Protocol):
    def append_event(self, db_path: Path, topic: str, payload: dict[str, Any]) -> int: ...
    def initialize_state_db(self, db_path: Path, log_exception: Any = None) -> None: ...


class FilesystemPort(Protocol):
    def read_text(self, path: Path | str, *, encoding: str = "utf-8", errors: str = "strict") -> str: ...
    def write_text(self, path: Path | str, text: str, *, encoding: str = "utf-8") -> None: ...
    def ensure_dir(self, path: Path | str) -> None: ...
    def touch(self, path: Path | str) -> None: ...
    def move(self, src: Path | str, dst: Path | str) -> None: ...
    def copy2(self, src: Path | str, dst: Path | str) -> None: ...
    def copytree(self, src: Path | str, dst: Path | str) -> None: ...
    def mkdtemp(self, *, prefix: str = "tmp") -> Path: ...
    def make_zip_archive(self, base_name: Path | str, *, root_dir: Path | str, base_dir: Path | str | None = None) -> Path: ...
    def rmtree(self, path: Path | str, *, ignore_errors: bool = False) -> None: ...
    def disk_usage(self, path: Path | str) -> tuple[int, int, int]: ...
    def can_write_dir(self, path: Path | str) -> bool: ...
